name = "queueada"
description = "A Queue implementation in Ada"
version = "0.1.0-dev"

authors = ["Elan Deyan Almeida"]
maintainers = ["Elan Deyan Almeida <elandeyandasilva@gmail.com>"]
maintainers-logins = ["ElanDeyan"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["data-structures", "queue"]
